// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTp89nGKt3t460trZh8_XKNvHGYEVozL8',
    appId: '1:444470006330:web:10d0a24170c6b2f93f1b03',
    messagingSenderId: '444470006330',
    projectId: 'graduation-project-11ad9',
    authDomain: 'graduation-project-11ad9.firebaseapp.com',
    storageBucket: 'graduation-project-11ad9.firebasestorage.app',
    measurementId: 'G-SZ8VJX3H9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB9n5p54I6XHahD-D5idXuhvV9TadsQaI',
    appId: '1:444470006330:android:394c7dba8954aa0c3f1b03',
    messagingSenderId: '444470006330',
    projectId: 'graduation-project-11ad9',
    storageBucket: 'graduation-project-11ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq2ACDuPmT94XlBvu60oPvYwFvFB2VLjM',
    appId: '1:444470006330:ios:0bbf9795ff2751e43f1b03',
    messagingSenderId: '444470006330',
    projectId: 'graduation-project-11ad9',
    storageBucket: 'graduation-project-11ad9.firebasestorage.app',
    iosBundleId: 'com.example.med360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq2ACDuPmT94XlBvu60oPvYwFvFB2VLjM',
    appId: '1:444470006330:ios:0bbf9795ff2751e43f1b03',
    messagingSenderId: '444470006330',
    projectId: 'graduation-project-11ad9',
    storageBucket: 'graduation-project-11ad9.firebasestorage.app',
    iosBundleId: 'com.example.med360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTp89nGKt3t460trZh8_XKNvHGYEVozL8',
    appId: '1:444470006330:web:4e5e5b20e955b8393f1b03',
    messagingSenderId: '444470006330',
    projectId: 'graduation-project-11ad9',
    authDomain: 'graduation-project-11ad9.firebaseapp.com',
    storageBucket: 'graduation-project-11ad9.firebasestorage.app',
    measurementId: 'G-7DFP6RXJDZ',
  );
}
